\set ON_ERROR_STOP on

-- Schema-only setup for first container initialization.
-- This file is mounted into docker-entrypoint-initdb.d and must not seed data.

create table if not exists item(
  id bigint primary key generated by default as identity,
  item_code text not null unique,
  created_at timestamp default now(),
  item_name text not null,
  max_stack_size bigint not null,
  item_type text not null default 'Ingredient'::text,
  max_durability bigint null
);

create table if not exists recipe(
  id bigint primary key generated by default as identity,
  recipe_code text not null unique,
  created_at timestamp default now(),
  target_item_id bigint not null,
  ingredient_item_id bigint not null,
  amount_needed bigint not null default '1'::bigint
);

create table if not exists enchantment(
  id bigint primary key generated by default as identity,
  enchantment_code text not null unique,
  created_at timestamp default now(),
  enchantment_name text not null,
  max_level bigint not null
);

create table if not exists player(
  id bigint primary key generated by default as identity,
  player_code text not null unique,
  created_at timestamp default now(),
  username text not null,
  current_xp_level bigint not null default '0'::bigint,
  health_points bigint not null default '20'::bigint,
  unique (username)
);

create table if not exists chest(
  id bigint primary key generated by default as identity,
  chest_code text not null unique,
  created_at timestamp default now(),
  x_coordinates bigint not null,
  y_coordinates bigint not null,
  z_coordinates bigint not null,
  dimension text not null default 'Overworld'::text
);

create table if not exists villager(
  id bigint primary key generated by default as identity,
  villager_code text not null unique,
  created_at timestamp default now(),
  villager_name text not null,
  profession text not null default 'Nitwit'::text,
  biome_type text not null default 'Plains'::text
);

-- (Muhammad Asad Aziz 67070503472)
create table if not exists "transfer"(
  id bigint primary key generated by default as identity,
  transfer_code text not null unique,
  created_at timestamp default now(),
  transfer_date timestamp without time zone null,
  player_id bigint null,
  source_chest_id bigint null,
  destination_chest_id bigint null
);

-- (Supanut Sopha 67070503441) Crafting header

create table if not exists crafting(
  id bigint primary key generated by default as identity,
  crafting_code text not null unique,
  created_at timestamp default now(),
  crafting_date timestamp without time zone null,
  session_id bigint null,
  player_id bigint null,
  target_item_id bigint null,
  qty_wanted bigint not null
);

--(Al Xander James Ybanez 67070503450)
CREATE TABLE IF NOT EXISTS smelting (
  id bigint primary key generated by default as identity,
  smelting_code text not null unique,
  created_at timestamp default now(),
  smelt_date timestamp,
  player_id bigint references player(id),
  furnace_location_xyz text not null
);

-- (Iris French 67070503478)
create table if not exists mining(
  id bigint primary key generated by default as identity,
  mining_code text not null unique,
  created_at timestamp default now(),
  mining_date timestamp,
  player_id bigint null,
  biome_name text null
);

-- (GUIDE) #1.1.1 ADD TABLES HERE

-- Line Items

-- (Muhammad Asad Aziz 67070503472)
create table if not exists transfer_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  transfer_id bigint null,
  transfer_line_number bigint not null,
  item_id bigint null,
  quantity_transferred bigint null,
  destination_slot_number bigint null
);

-- (Supanut Sopha 67070503441) Crafting line item

create table if not exists crafting_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  crafting_id bigint null,
  crafting_line_number bigint not null,
  session_id bigint null,
  ingredient_id bigint null,
  required_quantity bigint null,
  total_needed bigint null
);

--(Al Xander James Ybanez 67070503450) Smelting Line Items
CREATE TABLE IF NOT EXISTS smelting_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  smelting_id bigint references smelting(id) on delete cascade,
  raw_input_item_id bigint references item(id),
  quantity_inserted bigint,
  fuel_item_id bigint references item(id),
  fuel_consumed bigint,
  output_item_id bigint references item(id),
  output_quantity bigint
);

-- (Iris French 67070503478)
create table if not exists mining_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  mining_id bigint null,
  block_mined_id bigint null,
  quantity_mined bigint null,
  tool_used_id bigint null,
  durability_lost bigint null,
  tool_status text null
);

-- (GUIDE) #1.1.2 ADD LINE ITEMS HERE