\set ON_ERROR_STOP on

-- Schema-only setup for first container initialization.
-- This file is mounted into docker-entrypoint-initdb.d and must not seed data.

create table if not exists item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  item_name text not null,
  max_stack_size bigint not null,
  item_type text not null default 'Ingredient'::text,
  max_durability bigint null
);

create table if not exists recipe(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  target_item_id bigint not null,
  ingredient_item_id bigint not null,
  amount_needed bigint not null default '1'::bigint
);

create table if not exists enchantment(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  enchantment_name text not null,
  max_level bigint not null
);

create table if not exists player(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  username text not null,
  current_xp_level bigint not null default '0'::bigint,
  health_points bigint not null default '20'::bigint,
  unique (username)
);

create table if not exists chest(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  x_coordinates bigint not null,
  y_coordinates bigint not null,
  z_coordinates bigint not null,
  dimension text not null default 'Overworld'::text
);

create table if not exists villager(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  villager_name text not null,
  profession text not null default 'Nitwit'::text,
  biome_type text not null default 'Plains'::text
);

-- (Muhammad Asad Aziz 67070503472)
create table if not exists "transfer"(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  transfer_date timestamp without time zone null,
  player_id bigint null,
  source_chest_id bigint null,
  destination_chest_id bigint null
);

-- (GUIDE) #1.1.1 ADD TABLES HERE

-- Line Items

-- (Muhammad Asad Aziz 67070503472)
create table if not exists transfer_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  transfer_id bigint null,
  transfer_line_number bigint not null,
  item_id bigint null,
  quantity_transferred bigint null,
  destination_slot_number bigint null
);

-- (GUIDE) #1.1.2 ADD LINE ITEMS HERE