GET    http://localhost:4000/api/anvils
###
GET    http://localhost:4000/api/anvils/1
###
POST http://localhost:400/api/anvils    body{
                                                "anvil_date": "2026-05-31T12:00:00Z",
                                                "player_username": "Steve",
                                                "total_xp_cost": 3,
                                                "player_xp_before": 30,
                                                "player_xp_after": 27,
                                                "line_items": [
                                                    {
                                                    "target_tool_id": 20,
                                                    "current_durability": 150,
                                                    "sacrifice_item_id": 202,
                                                    "restored_durability": 250,
                                                    "enchantment_id": 5
                                                    }
                                                ]
                                            }

###

POST http://localhost:4000/api/anvils   body {
                                                "username": "Steve",
                                                "total_xp_cost": 5,
                                                "player_xp_before": 30,
                                                "player_xp_after": 25,
                                                "line_items": []
                                            }