\set ON_ERROR_STOP on

-- Schema-only setup for CraftLess
-- Safe to run multiple times: creates missing tables and indexes only.

create table if not exists item(
  id bigint primary key generated by default as identity,
  item_code text not null unique,
  created_at timestamp default now(),
  item_name text not null,
  max_stack_size bigint not null,
  item_type text not null default 'Ingredient'::text,
  max_durability bigint null
);

create table if not exists recipe(
  id bigint primary key generated by default as identity,
  recipe_code text not null unique,
  created_at timestamp default now(),
  target_item_id bigint not null,
  ingredient_item_id bigint not null,
  amount_needed bigint not null default '1'::bigint
);

create table if not exists enchantment(
  id bigint primary key generated by default as identity,
  enchantment_code text not null unique,
  created_at timestamp default now(),
  enchantment_name text not null,
  max_level bigint not null
);

create table if not exists player(
  id bigint primary key generated by default as identity,
  player_code text not null unique,
  created_at timestamp default now(),
  username text not null,
  current_xp_level bigint not null default '0'::bigint,
  health_points bigint not null default '20'::bigint,
  unique (username)
);

create table if not exists chest(
  id bigint primary key generated by default as identity,
  chest_code text not null unique,
  created_at timestamp default now(),
  x_coordinates bigint not null,
  y_coordinates bigint not null,
  z_coordinates bigint not null,
  dimension text not null default 'Overworld'::text
);

create table if not exists villager(
  id bigint primary key generated by default as identity,
  villager_code text not null unique,
  created_at timestamp default now(),
  villager_name text not null,
  profession text not null default 'Nitwit'::text,
  biome_type text not null default 'Plains'::text
);

-- (Muhammad Asad Aziz 67070503472)
create table if not exists "transfer"(
  id bigint primary key generated by default as identity,
  transfer_code text not null unique,
  created_at timestamp default now(),
  transfer_date timestamp without time zone null,
  player_id bigint null,
  source_chest_id bigint null,
  destination_chest_id bigint null
);

-- (Maimoona Aziz 67070503473) Anvil Header
create table if not exists "anvil"(
  id bigint primary key generated by default as identity,
  anvil_code text not null unique,
  created_at timestamp default now(),
  anvil_date timestamp without time zone null,
  player_id bigint null references player(id) on delete restrict on update cascade,
  total_xp_cost bigint null,
  player_xp_before bigint null,
  player_xp_after bigint null
);

--(Supanut Sopha 67070503441)
CREATE TABLE IF NOT EXISTS crafting (
    id SERIAL PRIMARY KEY,
    crafting_code text not null unique,
    crafting_date TIMESTAMP,
    session_id INTEGER, 
    player_id INTEGER REFERENCES player(id),
    target_item_id INTEGER REFERENCES item(id),
    qty_wanted INTEGER
);

--(Al Xander James Ybanez 67070503450)
CREATE TABLE IF NOT EXISTS smelting (
  id bigint primary key generated by default as identity,
  smelting_code text not null unique,
  created_at timestamp default now(),
  smelt_date timestamp,
  player_id bigint references player(id),
  furnace_location_xyz text not null
);

-- (Punyawat Sookarsa 67070503468)
CREATE TABLE IF NOT EXISTS trading_session (
  id bigint primary key generated by default as identity,
  trade_code text not null unique,
  created_at timestamp default now(),
  trade_date timestamp,
  player_name text not null,
  villager_id bigint references villager(id)
);

-- (Iris French 67070503478)
create table if not exists mining(
  id bigint primary key generated by default as identity,
  mining_code text not null unique,
  created_at timestamp default now(),
  mining_date timestamp,
  player_id bigint null,
  biome_name text null
);

-- (GUIDE) #1.1.3 ADD TABLES HERE

-------------
-- Line Items
-------------

-- (Muhammad Asad Aziz 67070503472)
create table if not exists transfer_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  transfer_id bigint null,
  transfer_line_number bigint not null,
  item_id bigint null,
  quantity_transferred bigint null,
  destination_slot_number bigint null
);

-- (Maimoona Aziz 67070503473) Anvil Line Item
create table if not exists anvil_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  anvil_id bigint null references anvil(id) on delete restrict on update cascade, -- anvil id FK
  anvil_line_number bigint not null,
  target_tool_id bigint null references item(id) on delete restrict on update cascade, -- target tool FK
  current_durability bigint null, -- current durability
  sacrifice_item_id bigint null references item(id) on delete restrict on update cascade, -- sacrifice item id FK
  restored_durability bigint null, -- restored durability
  enchantment_id bigint null references enchantment(id) on delete restrict on update cascade -- enchantment id FK
);

--(Supanut Sopha 67070503441)
CREATE TABLE IF NOT EXISTS crafting_line_item (
    id SERIAL PRIMARY KEY,
    crafting_id INTEGER REFERENCES crafting(id) ON DELETE CASCADE,
    crafting_line_number INTEGER,
    session_id INTEGER,
    ingredient_id INTEGER REFERENCES item(id), 
    required_quantity INTEGER,
    total_needed INTEGER
);

--(Al Xander James Ybanez 67070503450)
CREATE TABLE IF NOT EXISTS smelting_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  smelting_id bigint references smelting(id) on delete cascade,
  raw_input_item_id bigint references item(id),
  quantity_inserted bigint,
  fuel_item_id bigint references item(id),
  fuel_consumed bigint,
  output_item_id bigint references item(id),
  output_quantity bigint
);

-- (Punyawat Sookarsa 67070503468)
CREATE TABLE IF NOT EXISTS trading_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  trading_session_id bigint references trading_session(id) on delete cascade,
  line_number bigint not null,
  item_given_id bigint references item(id),
  quantity_given bigint not null default 1,
  item_received_id bigint references item(id),
  quantity_received bigint not null default 1,
  trade_uses_remaining bigint not null default 10
);

-- (Iris French 67070503478)
create table if not exists mining_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  mining_id bigint null,
  block_mined_id bigint null,
  quantity_mined bigint null,
  tool_used_id bigint null,
  durability_lost bigint null,
  tool_status text null
);

-- (GUIDE) #1.1.4 ADD LINE ITEMS HERE