-- Auto-generated SQL script to setup schema and load data
-- Example usage: psql -f sql_run.sql
-- Database: PostgreSQL (Docker)

-- ==========================================
-- 1. Schema Creation
-- ==========================================

DROP TABLE IF EXISTS transfer_line_item;
DROP TABLE IF EXISTS "transfer"; -- tranfer is orange (or IDE theme color same as DROP TABLE IF EXISTS) if I don't add the quotes... i think transfer is a command...
DROP TABLE IF EXISTS crafting_line_items;
DROP TABLE IF EXISTS crafting;
DROP TABLE IF EXISTS recipe;
DROP TABLE IF EXISTS villager;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS enchantment;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS chest;
-- (GUIDE) #1.3.1 ADD YOUR TABLE HERE

create table item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  item_name text not null,
  max_stack_size bigint not null,
  item_type text not null default 'Ingredient'::text,
  max_durability bigint null
);

create table recipe(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  target_item_id bigint not null,
  ingredient_item_id bigint not null,
  amount_needed bigint not null default '1'::bigint
);

create table enchantment(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  enchantment_name text not null,
  max_level bigint not null
);

create table player(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  username text not null,
  current_xp_level bigint not null default '0'::bigint,
  health_points bigint not null default '20'::bigint,
  unique (username)
);

create table chest(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  x_coordinates bigint not null,
  y_coordinates bigint not null,
  z_coordinates bigint not null,
  dimension text not null default 'Overworld'::text
);

create table villager(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  villager_name text not null,
  profession text not null default 'Nitwit'::text,
  biome_type text not null default 'Plains'::text
);

-- (Muhammad Asad Aziz 67070503472)
create table "transfer"(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  transfer_date timestamp without time zone null,
  player_id bigint null,
  source_chest_id bigint null,
  destination_chest_id bigint null
);

-- (Supanut Sopha 67070503441) Crafting
create table crafting(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  crafting_date timestamp without time zone null,
  session_id bigint null,
  player_id bigint null,
  target_item_id bigint null,
  qty_wanted bigint not null
);

-- (GUIDE) #1.3.2 ADD TABLES HERE

-- Line Items

-- (Muhammad Asad Aziz 67070503472)
create table transfer_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  transfer_id bigint null,
  transfer_line_number bigint not null,
  item_id bigint null,
  quantity_transferred bigint null,
  destination_slot_number bigint null
);

-- (Supanut Sopha 67070503441) Crafting line items

create table crafting_line_item(
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  crafting_id bigint null,
  crafting_line_number bigint not null,
  session_id bigint null,
  ingredient_id bigint null,
  required_quantity bigint null,
  total_needed bigint null
);

-- (GUIDE) #1.3.3 ADD LINE ITEMS HERE

-- Indexes
CREATE INDEX IF NOT EXISTS idx_transfer_date ON "transfer"(transfer_date);                  -- Transfers that happened within a specific date range
CREATE INDEX IF NOT EXISTS idx_transfer_player ON "transfer"(player_id);                    -- Transfers made by a specific player
CREATE INDEX IF NOT EXISTS idx_transfer_source_chest ON "transfer"(source_chest_id);        -- Tracking chest inventory movements
CREATE INDEX IF NOT EXISTS idx_transfer_dest_chest ON "transfer"(destination_chest_id);     -- Tracking chest inventory movements
CREATE INDEX IF NOT EXISTS idx_transfer_line_transfer ON transfer_line_item(transfer_id);   -- Getting all line items that belong to a single transfer
CREATE INDEX IF NOT EXISTS idx_transfer_line_item ON transfer_line_item(item_id);           -- How often a specific item was transferred
CREATE INDEX IF NOT EXISTS idx_recipe_target_item ON recipe(target_item_id);                -- Looking up crafting recipes
CREATE INDEX IF NOT EXISTS idx_recipe_ingredient_item ON recipe(ingredient_item_id);        -- Looking up crafting recipes
-- (GUIDE) #1.3.4 Add indexes here (I think it's for performance reasons, so it's ok to ignore if dunno how to)


-- ==========================================
-- 2. Data Insertion
-- ==========================================

-- Populating table: item
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Oak Log', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Oak Planks', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Stick', 64, 'Ingredient', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Iron Ore', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Iron Ingot', 64, 'Ingredient', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Coal', 64, 'Ingredient', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Diamond', 64, 'Ingredient', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Iron Pickaxe', 1, 'Tool', 250);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Diamond Sword', 1, 'Tool', 1561);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Emerald', 64, 'Ingredient', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Rotten Flesh', 64, 'Food', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Cobblestone', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Stone', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Gold Ore', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Gold Ingot', 64, 'Ingredient', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Bread', 64, 'Food', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Wheat', 64, 'Ingredient', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Sand', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Glass', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Iron Axe', 1, 'Tool', 250);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Torch', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Crafting Table', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Furnace Block', 64, 'Block', null);
INSERT INTO item (item_name, max_stack_size, item_type, max_durability) VALUES ('Diamond Pickaxe', 1, 'Tool', 1561);

-- Populating table: recipe
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (2, 1, 1);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (3, 2, 2);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (16, 17, 3);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (8, 5, 3);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (8, 3, 2);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (9, 7, 2);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (9, 3, 1);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (20, 5, 3);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (20, 3, 2);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (21, 6, 1);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (21, 3, 1);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (24, 7, 3);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (24, 3, 2);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (22, 2, 4);
INSERT INTO recipe (target_item_id, ingredient_item_id, amount_needed) VALUES (23, 12, 8);

-- Populating table: enchantment
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Unbreaking', 3);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Sharpness', 5);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Fortune', 3);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Efficiency', 5);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Protection', 4);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Silk Touch', 1);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Mending', 1);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Fire Aspect', 2);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Looting', 3);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Knockback', 2);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Power', 5);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Punch', 2);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Flame', 1);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Infinity', 1);
INSERT INTO enchantment (enchantment_name, max_level) VALUES ('Thorns', 3);

-- Populating table: player
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Steve', 30, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Alex', 15, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Herobrine', 99, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Notch', 50, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Jeb_', 40, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Dream', 25, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Technoblade', 80, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('DanTDM', 12, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('CaptainSparklez', 45, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Stampy', 22, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('MumboJumbo', 60, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Grian', 18, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('TommyInnit', 5, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('WilburSoot', 14, 20);
INSERT INTO player (username, current_xp_level, health_points) VALUES ('Philza', 65, 20);

-- Populating table: chest
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (100, 64, 250, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (101, 64, 250, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (102, 64, 250, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (15, 40, -50, 'Nether');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (16, 40, -50, 'Nether');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (200, 70, 300, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (-500, 64, -500, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (0, 120, 0, 'The End');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (10, 30, 10, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (11, 30, 10, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (-100, 64, 800, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (50, 50, 50, 'Nether');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (20, 64, 20, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (21, 64, 20, 'Overworld');
INSERT INTO chest (x_coordinates, y_coordinates, z_coordinates, dimension) VALUES (22, 64, 20, 'Overworld');

-- Populating table: villager
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Bob', 'Cleric', 'Plains');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Testificate', 'Weaponsmith', 'Taiga');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Dan', 'Fletcher', 'Desert');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Gary', 'Farmer', 'Savanna');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Larry', 'Librarian', 'Plains');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Gerry', 'Armorer', 'Snowy Tundra');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Terry', 'Toolsmith', 'Desert');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Barry', 'Butcher', 'Taiga');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Mary', 'Leatherworker', 'Swamp');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Harry', 'Mason', 'Plains');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Jerry', 'Shepherd', 'Savanna');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Perry', 'Cartographer', 'Desert');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Tom', 'Cleric', 'Snowy Tundra');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Dick', 'Farmer', 'Plains');
INSERT INTO villager (villager_name, profession, biome_type) VALUES ('Jane', 'Librarian', 'Taiga');

-- Muhammad Asad Aziz 67070503472
-- Populating table: transfer
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2024-05-14 20:10:00', 1, null, 1);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2024-06-25 21:15:30', 2, 1, 2);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2024-08-11 22:45:12', 3, null, 3);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2024-11-06 23:20:05', 4, 3, 4);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2025-01-20 08:05:55', 5, null, 5);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2025-03-15 09:30:40', 6, 5, 6);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2025-06-01 10:11:11', 7, null, 7);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2025-07-15 11:40:20', 8, 7, 8);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2025-09-05 12:55:34', 9, null, 9);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2025-10-20 13:25:50', 10, 9, 10);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2025-12-28 14:00:15', 11, null, 11);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2026-01-15 15:18:44', 12, 11, 12);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2026-02-08 16:33:21', 13, null, 13);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2026-02-22 17:10:09', 14, 13, 14);
INSERT INTO transfer (transfer_date, player_id, source_chest_id, destination_chest_id) VALUES ('2026-03-22 18:05:01', 15, null, 15);

-- Supanut Sopha 67070503441
-- Populating table: crafting

INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 18:05:01', 1, 1, null, 1);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 18:15:01', 2, 2, null, 2);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 18:25:01', 3, 3, null, 3);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 18:35:01', 4, 4, null, 4);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 18:45:01', 5, 5, null, 5);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 18:55:01', 6, 6, null, 6);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 19:05:01', 7, 7, null, 7);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 19:15:01', 8, 8, null, 8);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 19:25:01', 9, 9, null, 9);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 19:35:01', 10, 10, null, 10);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 19:45:01', 11, 11, null, 11);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 19:55:01', 12, 12, null, 12);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 20:05:01', 13, 13, null, 13);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 20:15:01', 14, 14, null, 14);
INSERT INTO crafting (crafting_date, session_id, player_id, target_item_id, qty_wanted) VALUES ('2026-03-22 20:25:01', 15, 15, null, 15);

-- (GUIDE) #1.3.5  POPULATE SIMPLE FORMS HERE, WITHOUT THE "ON CONFLICT DO NOTHING" part


-- Line Items

-- Populating table: transfer_line_item
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (1, 1, 7, 5, 1);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (1, 2, 5, 10, 2);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (1, 3, 12, 64, 3);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (2, 1, 5, 32, 2);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (3, 1, 1, 64, 1);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (4, 1, 2, 64, 3);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (5, 1, 12, 64, 1);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (6, 1, 13, 32, 4);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (7, 1, 18, 64, 1);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (8, 1, 19, 16, 5);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (9, 1, 14, 10, 1);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (10, 1, 15, 20, 6);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (11, 1, 4, 40, 1);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (12, 1, 6, 64, 7);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (13, 1, 10, 15, 1);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (14, 1, 11, 64, 8);
INSERT INTO transfer_line_item (transfer_id, transfer_line_number, item_id, quantity_transferred, destination_slot_number) VALUES (15, 1, 16, 10, 1);


-- Populating table: crafting_line_item
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (1, 1, 1, 12, 3, 2);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (2, 1, 2, 5, 1, 4);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (3, 1, 3, 8, 6, 1);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (4, 1, 4, 15, 2, 5);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (5, 1, 5, 2, 7, 3);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (6, 1, 6, 11, 4, 2);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (7, 1, 7, 3, 5, 1);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (8, 1, 8, 16, 2, 4);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (9, 1, 9, 7, 1, 3);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (10, 1, 10, 14, 6, 5);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (11, 1, 11, 9, 3, 2);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (12, 1, 12, 4, 7, 1);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (13, 1, 13, 1, 5, 4);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (14, 1, 14, 10, 2, 3);
INSERT INTO crafting_line_item (crafting_id, crafting_line_number, session_id, ingredient_id, required_quantity, total_needed) VALUES (15, 1, 15, 13, 4, 5);

-- (GUIDE) #1.3.6 POPULATE LINE ITEMS HERE, WITHOUT THE "ON CONFLICT DO NOTHING" part


-- update sequences to max id (crutial when inserting explicit IDs)
SELECT setval(pg_get_serial_sequence('item', 'id'), coalesce(max(id),0) + 1, false) FROM item;
SELECT setval(pg_get_serial_sequence('recipe', 'id'), coalesce(max(id),0) + 1, false) FROM recipe;
SELECT setval(pg_get_serial_sequence('enchantment', 'id'), coalesce(max(id),0) + 1, false) FROM enchantment;
SELECT setval(pg_get_serial_sequence('player', 'id'), coalesce(max(id),0) + 1, false) FROM player;
SELECT setval(pg_get_serial_sequence('chest', 'id'), coalesce(max(id),0) + 1, false) FROM chest;
SELECT setval(pg_get_serial_sequence('villager', 'id'), coalesce(max(id),0) + 1, false) FROM villager;
SELECT setval(pg_get_serial_sequence('transfer', 'id'), coalesce(max(id),0) + 1, false) FROM transfer;
SELECT setval(pg_get_serial_sequence('transfer_line_item', 'id'), coalesce(max(id),0) + 1, false) FROM transfer_line_item;


SELECT setval(pg_get_serial_sequence('crafting', 'id'), coalesce(max(id),0) + 1, false) FROM crafting;
SELECT setval(pg_get_serial_sequence('crafting_line_item', 'id'), coalesce(max(id),0) + 1, false) FROM crafting_line_item;
-- (GUIDE) #1.3.7 ADD SELECT COMMAND FOR YOUR SIMPLE FORM AND LINE ITEM HERE (just copy and rename)
-- SELECT setval(pg_get_serial_sequence('TABLE_NAME', 'id'), coalesce(max(id),0) + 1, false) FROM TABLE_NAME;
